import React,{useEffect,useState} from 'react';
import {request} from './request';
import DownloadCandidateLinks from './DownloadCandidateLinks';

const states:Record<string,string>={MET:'Đáp ứng',PARTIAL:'Đáp ứng một phần',NOT_MET:'Có bằng chứng chưa đáp ứng',UNKNOWN:'Chưa đủ thông tin'};
const lanes:Record<string,string>={QUALIFIED:'Đáp ứng điều kiện hiện tại',NEEDS_VERIFICATION:'Cần xác minh',BELOW_POLICY:'Dưới điều kiện hiện tại'};
export default function AllSourceAssessment({searchId,jobId,version,total}:{searchId:string;jobId:string;version:number;total:number}){
 const [report,setReport]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[limit,setLimit]=useState(10),[texts,setTexts]=useState<Record<string,any>>({});
 const [preview,setPreview]=useState<any>(null);
 const working=report&&['PENDING','RUNNING'].includes(report.status);
 const canRetry=report?.is_current&&[...(report.content_fetches||[]),...(report.batches||[])].some((c:any)=>['FAILED','PARTIAL','INTERRUPTED'].includes(c.status)&&(c.attempts||0)<3);
 const load=async()=>{const h=await request<any[]>('/v1/people-searches/'+searchId+'/assessment-groups');setHistory(h);return h};
 useEffect(()=>{let active=true;load().then(async h=>{if(h.length){const r=await request('/v1/assessment-groups/'+h[0].id);if(active)setReport(r)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[searchId]);
 useEffect(()=>{let active=true;request('/v1/people-searches/'+searchId+'/assessment-group-preview?config_version='+version).then(p=>{if(active)setPreview(p)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[searchId,version]);
 useEffect(()=>{if(!working)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await request<any>('/v1/assessment-groups/'+report.id);if(active){setReport(r);if(['PENDING','RUNNING'].includes(r.status))timer=setTimeout(poll,1500)}}catch(e){if(active){setError((e as Error).message);timer=setTimeout(poll,3000)}}};poll();return()=>{active=false;clearTimeout(timer)}},[report?.id,!!working]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const start=()=>act(async()=>{setReport(await request('/v1/people-searches/'+searchId+'/assessment-groups','POST',{config_version:version}));setTexts({});setLimit(10);await load()});
 return <section className="assessment"><h2>Lấy nội dung và đánh giá tất cả nguồn</h2>
 <p>Tìm được <b>{total} nguồn hồ sơ công khai</b> sau khi gom link trùng. Hệ thống lấy nội dung rồi tự chia nhóm AI vừa giới hạn kỹ thuật; không cần kho CV.</p>
 <p>Thao tác này có phí lấy nội dung và AI. Số call phụ thuộc độ dài nội dung và cache, chưa đủ dữ liệu để dự toán tiền. Mỗi lượt lấy nội dung tối đa 20 nguồn; AI chấm tối đa 5 hồ sơ mỗi batch và còn phải vừa giới hạn kỹ thuật, chạy tuần tự. Không đảm bảo lấy toàn bộ LinkedIn.</p>
 <p>Nguồn không lấy được text hoặc quá dài để chấm riêng sẽ được giữ với lý do; không tự dùng đoạn trích, cắt nội dung hoặc đổi model.</p>
 {preview&&preview.total_sources<total&&<p className="notice">{total} URL tìm được tương ứng {preview.total_sources} hồ sơ sau khi gom các đường dẫn LinkedIn trùng. Giữ tất cả hướng tìm nguồn; không gom người theo tên.</p>}
 {preview&&<p className="notice">Kiểm tra cache: {preview.cached_available}/{preview.total_sources} nguồn có text trong 24 giờ; {preview.needs_content} nguồn cần lấy nội dung. Phần đã có text dự kiến {preview.cached_batches.length} batch AI; số batch cuối tùy nội dung lấy thêm. Chưa gọi provider hoặc phát sinh phí.</p>}
 {preview&&!preview.model_budget.verified&&<p className="notice warn">Cần xác nhận giới hạn context/output của model trong thiết lập trước khi xử lý; hệ thống không tự đổi model.</p>}
 <button disabled={busy||!!working||!total||!preview?.model_budget.verified} onClick={start}>{working?'Đang xử lý — không cần bấm lại':`Lấy nội dung & đánh giá tất cả ${total} nguồn — có phí`}</button>
 {error&&<p className="notice error" role="alert">{error}</p>}
 {report&&<><p role="status"><b>{report.status==='COMPLETED'?'Đã xử lý toàn bộ':report.status==='PARTIAL'?'Hoàn tất một phần — còn nguồn chưa chấm':working?'Đang xử lý':'Chưa hoàn tất'}</b><br/>Tìm được {report.total_sources} → Đã lấy nội dung {report.content_available}/{report.total_sources} → Đã chấm {report.assessed_sources}/{report.content_available}</p>
 <p>Mã lượt: {report.id} · {report.provider}/{report.model} · {report.elapsed_seconds} giây (gồm thời gian chờ)</p>
 {!report.is_current&&<p className="notice warn">Yêu cầu, model hoặc phiên bản bộ chấm đã đổi. Lượt này giữ snapshot cũ; tạo lượt theo yêu cầu hiện tại để cập nhật.</p>}
 {report.error&&<p role="alert" className="notice error">{report.error}</p>}
 <p>Phí lấy nội dung provider đã báo: ${Number(report.content_cost_dollars||0).toFixed(5)}{report.content_cost_unreported?' · Có lượt chưa xác định phí.':''} · Usage AI: {report.total_tokens||0} token đã báo. Phí AI chưa được provider xác nhận. Chi phí của lượt con dùng lại được giữ trong lịch sử; không phải hóa đơn mới.</p>
 <details><summary>Tiến trình từng lượt con ({report.content_fetches.length} lấy nội dung, {report.batches.length} batch AI)</summary>{report.content_fetches.map((f:any,i:number)=><p key={f.id||i}>Lấy nội dung {i+1}: {f.source_count} nguồn · {f.status} · {f.attempts||0}/3 lần thử</p>)}{report.batches.map((b:any,i:number)=><p key={b.assessment_id||i}>AI batch {i+1}: {b.urls.length} nguồn · {b.status} · {b.attempts}/3 lần thử {b.error&&'· '+b.error}</p>)}</details>
 {report.status==='PARTIAL'&&canRetry&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{setReport(await request('/v1/assessment-groups/'+report.id+'/retry','POST'));await load()})}>Thử lại phần lỗi còn lượt thử (có phí)</button>}
 {report.status==='PARTIAL'&&report.is_current&&!canRetry&&<p className="notice warn">Không còn lượt con có thể thử lại. Kết quả đã chấm được giữ nguyên; xem lỗi từng batch và bổ sung hồ sơ hoặc cập nhật bộ chấm trước khi tạo lượt mới.</p>}
 {!!report.results.length&&<><label>Hiển thị TopK<select aria-label="TopK nhóm tất cả nguồn" value={Math.min(limit,report.results.length)} onChange={e=>setLimit(+e.target.value)}>{Array.from({length:report.results.length},(_,i)=>i+1).map(n=><option key={n} value={n}>Top {n}</option>)}</select></label>
 <DownloadCandidateLinks results={report.results} limit={limit} jobId={jobId} runId={report.id} provisional={report.provisional}/><p className="muted">{report.provisional?'Kết quả tạm thời từ các batch đã validate; thứ hạng có thể thay đổi khi chấm tiếp. ':'Kết quả từ các batch đã validate. '}Đổi TopK chỉ đọc kết quả lưu. Điểm đáp ứng có bằng chứng, không phải xác suất tuyển dụng. Policy và độ ổn định giữa các batch chưa benchmark bằng nhãn khách.</p>
 {report.results.slice(0,limit).map((r:any)=><article className="search-direction" key={r.candidate_id}><div className="card-head"><h3><a href={r.url} target="_blank" rel="noreferrer">{r.title||r.url}</a></h3><strong>{r.score??'—'} / 100</strong></div>
 <p>Độ phủ bằng chứng: {r.coverage}% · MUST chưa rõ: {r.assessments.filter((a:any)=>a.status==='UNKNOWN'&&report.criteria.find((c:any)=>c.id===a.criterion_id)?.type==='MUST').length} · {lanes[r.lane]||'Cần xác minh'} · Địa điểm cần xác minh</p>
 <details onToggle={e=>{if(e.currentTarget.open&&!texts[r.candidate_id])act(async()=>{const text=await request('/v1/assessment-groups/'+report.id+'/sources/'+r.candidate_id);setTexts(v=>({...v,[r.candidate_id]:text}))})}}><summary>Xem đúng nội dung đã chấm</summary>{texts[r.candidate_id]?<><p>Revision {texts[r.candidate_id].revision} · {texts[r.candidate_id].provider_source} · {texts[r.candidate_id].fetched_at}</p>{texts[r.candidate_id].warnings?.map((w:string)=><p key={w} className="notice warn">{w}</p>)}<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{texts[r.candidate_id].text}</pre></>:<p>Đang tải nội dung…</p>}</details>
 <details><summary>Tiêu chí, bằng chứng và câu hỏi xác minh</summary>{r.assessments.map((a:any)=><div className="assessment" key={a.criterion_id}><b>{report.criteria.find((c:any)=>c.id===a.criterion_id)?.name||a.criterion_id} · {states[a.status]}</b><p>{a.explanation}</p>{a.evidence?.map((ev:any,i:number)=><blockquote key={i}><small>Đoạn {ev.paragraph_id} · revision {ev.revision}</small><p>{ev.quote}</p></blockquote>)}{a.questions?.map((q:string)=><p key={q}>Cần hỏi: {q}</p>)}</div>)}</details>
 <a href={'/api/v1/public-assessments/'+r.assessment_id+'/export'} download>Tải input/output batch này</a></article>)}</>}
 <details open={report.status==='PARTIAL'}><summary>Nguồn chưa chấm ({report.unassessed_sources.length})</summary>{report.unassessed_sources.map((s:any)=><div className="assessment" key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title||s.url}</a><p>{s.status} · {s.reason}</p></div>)}{!!report.unassessed_sources.length&&<p>Có thể dùng phần “Chấm nhóm riêng” bên dưới để bổ sung PDF đúng người hoặc chủ động xác nhận chấm đoạn trích. Kết quả lượt này được giữ nguyên.</p>}</details></>}
 <details><summary>Lịch sử xử lý tất cả nguồn ({history.length})</summary>{history.map(h=><div className="actions" key={h.id}><small>{new Date(h.created).toLocaleString('vi-VN')} · {h.status}</small><button className="secondary" disabled={busy||!!working} onClick={()=>act(async()=>{setReport(await request('/v1/assessment-groups/'+h.id));setTexts({});setLimit(10)})}>Mở lượt</button></div>)}</details>
 </section>;
}
