import React,{useEffect,useState} from 'react';
import {request} from './request';

type Item={candidate_id:string;score:number;coverage:number;lane:string;be_rank:number;strengths:string[];gaps:string[];recommendation?:string;assessments:{criterion_id:string;status:string;explanation:string;evidence:{source_id:string;quote:string}[];questions?:string[]}[]};
type Search={scope?:string;id:string;job_id:string;config_version:number;status:string;is_current:boolean;input_count:number;pool_size:number;created:string;preview:Item[];stream_supported:boolean;attempts:number;error?:string;result_run_id?:string;provider:string;model:string;config:any;results:Item[];be_results:Item[];group:Record<string,{title:string;sources:any[]}>;usage:any[];budget?:{assessment_reused_from?:string}};
const lanes:Record<string,string>={QUALIFIED:'Đáp ứng điều kiện hiện tại',NEEDS_VERIFICATION:'Cần xác minh',BELOW_POLICY:'Dưới điều kiện hiện tại'};
const states:Record<string,string>={MET:'Đáp ứng',PARTIAL:'Một phần',NOT_MET:'Không đáp ứng',UNKNOWN:'Chưa đủ thông tin'};
export default function BatchSearch({id,onJob,onCompare,onFeedback,sheetsConnected}:{id:string;onJob:(job:string)=>void;onCompare:(run:string,ids:string[])=>Promise<void>;onFeedback:(run:string,id:string)=>void;sheetsConnected:boolean}){
 const [search,setSearch]=useState<Search|null>(null),[error,setError]=useState(''),[display,setDisplay]=useState(10),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[input,setInput]=useState(20),[refreshKey,setRefreshKey]=useState(0),[exports,setExports]=useState<any[]>([]),[benchmark,setBenchmark]=useState<any>(null);
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;let events:EventSource|null=null;setSearch(null);setSelected([]);setDisplay(10);setError('');
 const apply=(s:Search)=>{if(!active)return;setSearch(s);setError('');if(!['PENDING','RUNNING'].includes(s.status))events?.close()};
 const poll=async()=>{try{const s=await request<Search>('/v1/searches/'+id);apply(s);if(active&&['PENDING','RUNNING'].includes(s.status))timer=setTimeout(poll,2000)}catch(e){if(active){setError((e as Error).message);timer=setTimeout(poll,5000)}}};
 const start=async()=>{try{const s=await request<Search>('/v1/searches/'+id);apply(s);if(!active||!['PENDING','RUNNING'].includes(s.status))return;events=new EventSource('/api/v1/searches/'+id+'/events');events.onmessage=e=>{try{apply(JSON.parse(e.data))}catch{events?.close();timer=setTimeout(poll,2000)}};events.onerror=()=>{events?.close();if(active)timer=setTimeout(poll,2000)}}catch{poll()}};start();return()=>{active=false;events?.close();clearTimeout(timer)}},[id,refreshKey]);
 const [clock,setClock]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);

 useEffect(()=>{if(!search?.result_run_id)return;let active=true;let timer:ReturnType<typeof setTimeout>;const run=search.result_run_id;const refresh=async()=>{try{const values=await request<any[]>('/runs/'+run+'/sheets');if(active){setExports(values);timer=setTimeout(refresh,5000)}}catch{}};refresh();return()=>{active=false;clearTimeout(timer)}},[search?.result_run_id]);
 const retry=async()=>{if(!search)return;setBusy(true);try{const r=await request<{search_id:string}>(search.scope==='single-cv'?'/v1/searches/'+id+'/retry':'/v1/jobs/'+search.job_id+'/searches','POST',search.scope==='single-cv'?undefined:{config_version:search.config_version,candidate_limit:input});window.dispatchEvent(new CustomEvent('pilot-search-reopen',{detail:{id:r.search_id}}));setRefreshKey(k=>k+1);}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(!search)return <section className="card" role="status">{error||'Đang tải lượt tìm kiếm…'}</section>;
 const done=search.results.length>0,working=['PENDING','RUNNING'].includes(search.status);
 const partial=!done&&(search.preview?.length??0)>0;const hasAI=done||partial;
 const all=done?search.results:partial?search.preview:search.be_results;
 const elapsed=Math.max(0,Math.floor((clock-Date.parse(search.created))/1000));
 const visible=all.slice(0,Math.min(display,all.length));
 const single=search.scope==='single-cv';
 const title=single?(working?'Đang đánh giá CV với job':done?'Kết quả đánh giá CV với job':'Chưa đánh giá được CV'):working?(search.status==='RUNNING'?`Đang đánh giá ${search.input_count} người`:'Đang chờ đánh giá AI'):done?'Đã đánh giá và xếp hạng':'AI chưa đánh giá được nhóm này';
 return <div className="batch-search"><section className="card"><div className="card-head"><div><span className="code">{search.job_id}</span><h2>{title}</h2></div><button className="secondary" onClick={()=>onJob(search.job_id)}>Xem yêu cầu</button></div><ol className="journey" aria-label="Tiến trình tìm ứng viên"><li className="done"><span>1</span> {single?'CV bạn đã tải lên':`Tìm trong ${search.pool_size} hồ sơ`}</li><li className={working?'current':done?'done':''}><span>2</span> AI đánh giá {search.input_count} người</li><li className={done?'done':''}><span>3</span> Xem kết quả</li></ol><p>{search.provider} / {search.model} · Yêu cầu v{search.config_version}. Một nhóm gửi AI; không đọc lại PDF CV.</p>{search.budget?.assessment_reused_from&&<p className="notice">Đã dùng lại kết quả đã kiểm chứng; không gửi lại nhóm hồ sơ. </p>}{working&&<p role="status">{search.stream_supported?`Đã nhận ${search.preview?.length??0}/${search.input_count} hồ sơ đã kiểm tra. Kết quả hiện dần; thứ hạng chưa chốt.`:"Provider này trả cả nhóm khi hoàn tất; chưa hỗ trợ hiển thị dần."} Đã chờ {elapsed} giây{search.attempts>1?` · đang thử lần ${search.attempts}/3`:""}. {elapsed>120?"Lượt này đang lâu hơn mục tiêu 2 phút. ":""}Bạn không cần gửi lại.</p>}{!search.is_current&&<div className="notice warn">Dữ liệu hoặc yêu cầu đã thay đổi. Đây là kết quả cũ.<button onClick={()=>onJob(search.job_id)}>Cập nhật tìm kiếm</button></div>}{search.error&&<div className="notice error" role="alert">{search.error.startsWith('JSON schema:')?'AI trả dữ liệu chưa hợp lệ. Kết quả BE vẫn được giữ; xem chi tiết lỗi bên dưới.':search.error}</div>}{!working&&!done&&search.is_current&&<div className="actions">{!single&&<label>Số người gửi AI <input aria-label="Số người gửi AI khi thử lại" type="number" min="1" max="20" value={input} onChange={e=>setInput(Math.max(1,Math.min(20,+e.target.value)))}/></label>}<button disabled={busy||(search.attempts>=3&&(single||input===search.input_count))} onClick={retry}>Thử đánh giá nhóm</button><small>Đã thử {search.attempts}/3 lần. Đổi nhóm hoặc model nếu đã hết lượt thử.</small></div>}</section>
 <section className="card"><div className="card-head"><div><h3>{done?'Kết quả sau đánh giá AI':partial?'Kết quả đang về · chưa chốt thứ hạng':'Nhóm BE đã tìm thấy · chưa đánh giá AI'}</h3><p>Đáp ứng: {hasAI?all.filter(r=>r.lane==='QUALIFIED').length:'—'} · Cần xác minh: {hasAI?all.filter(r=>r.lane==='NEEDS_VERIFICATION').length:'—'} · Tổng: {all.length}</p></div><label>Hiển thị <select aria-label="Số kết quả hiển thị" value={Math.min(display,Math.max(all.length,1))} onChange={e=>setDisplay(+e.target.value)}>{Array.from({length:Math.max(all.length,1)},(_,i)=><option key={i} value={i+1}>{i+1} hồ sơ</option>)}</select></label></div><p className="muted">Thay số hiển thị không gọi AI lại. Điểm là mức đáp ứng có bằng chứng, không phải xác suất tuyển dụng. {search.config.policy?.calibrated?'Policy đã đối chiếu nhãn.':'Policy chưa benchmark với nhãn khách xác nhận.'}</p>{!hasAI&&<p className="notice warn">Điểm dưới đây là điểm BE để retrieval. Chỉ dùng tham khảo khi AI chưa hoàn tất.</p>}{done&&!all.some(r=>r.lane==='QUALIFIED')&&<p className="notice warn">Chưa ai đáp ứng đủ điều kiện hiện tại. Các hồ sơ vẫn được hiển thị để bạn xem bằng chứng và xác minh.</p>}
 {visible.map((item,i)=><article className="candidate-result" key={item.candidate_id}><div className="candidate-result-head"><label><input type="checkbox" aria-label={'Chọn '+item.candidate_id} disabled={!done||!search.is_current||working} checked={selected.includes(item.candidate_id)} onChange={()=>setSelected(s=>s.includes(item.candidate_id)?s.filter(x=>x!==item.candidate_id):[...s,item.candidate_id])}/></label><div><span>{single?(search.group[item.candidate_id]?.sources.find((s:any)=>s.group==='candidate_public')?.name||item.candidate_id):`${partial?"Đã nhận":`#${i+1}`} · ${item.candidate_id}`}</span><h3>{search.group[item.candidate_id]?.title}</h3><span className="badge">{hasAI?lanes[item.lane]:'Chưa đánh giá AI'}</span></div><div className="score"><b>{item.score}</b><small>{done?'Điểm sau đánh giá AI':partial?'Điểm tạm · chưa chốt':'Điểm BE'}</small></div></div><p>Độ phủ bằng chứng: {item.coverage}%</p>{single&&hasAI&&item.recommendation&&<p className="notice">{item.recommendation}</p>}<p>{hasAI?item.assessments.filter(a=>a.status==='MET').slice(0,2).map(a=>search.config.criteria.find((c:any)=>c.id===a.criterion_id)?.name||a.criterion_id).join(' · ')||'Chưa có yêu cầu được xác nhận đáp ứng.':item.strengths?.slice(0,2).join(' · ')}</p>{hasAI&&item.assessments.some(a=>a.status==='UNKNOWN')&&<p className="muted">Chưa có đủ bằng chứng cho {item.assessments.filter(a=>a.status==='UNKNOWN').length} yêu cầu; cần hỏi thêm.</p>}<div className="actions">{done&&<button className="text-button" disabled={!search.is_current||busy} onClick={()=>onFeedback(search.result_run_id!,item.candidate_id)}>Ghi đánh giá</button>}</div><details><summary>Xem cách tính điểm, bằng chứng và câu hỏi</summary><p>Điểm = tổng (trọng số × mức đáp ứng) / tổng trọng số. Đáp ứng: 100; một phần: 50; không đáp ứng: 0. UNKNOWN không có điểm được xác nhận và được theo dõi riêng qua độ phủ.</p>{item.assessments.map(a=>{const c=search.config.criteria.find((x:any)=>x.id===a.criterion_id);const source=(sid:string)=>search.group[item.candidate_id]?.sources.find(s=>s.source_id===sid);return <div className="assessment" key={a.criterion_id}><b>{c?.name||a.criterion_id} · {states[a.status]}</b><small>Trọng số {search.config.policy?.weights?.[c?.type]??'—'}</small><p>{a.explanation}</p>{a.evidence.map((e,n)=><blockquote key={n}>{e.quote}<small><a href={source(e.source_id)?.url} target="_blank" rel="noreferrer">{source(e.source_id)?.name||e.source_id} · nguồn revision {source(e.source_id)?.revision}</a></small></blockquote>)}{a.questions?.map((q,n)=><p key={n}>Cần hỏi: {q}</p>)}</div>})}<p>Gợi ý xem hồ sơ: {item.recommendation}</p><p>BE: hạng {item.be_rank} · điểm {search.be_results.find(x=>x.candidate_id===item.candidate_id)?.score}. Điểm này không gửi cho AI chấm.</p></details></article>)}
 </section>{done&&<details className="card"><summary>Xuất kết quả và đối chiếu chất lượng</summary><p>Xuất {Math.min(display,all.length)} hồ sơ theo thứ hạng AI, kèm trạng thái từng người; không chỉ xuất nhóm đạt điều kiện.</p><div className="actions"><a className="secondary" href={'/api/runs/'+search.result_run_id+'/shortlist.csv?top_k='+display}>Tải CSV</a><button disabled={!sheetsConnected||busy||!search.is_current} onClick={async()=>{setBusy(true);try{await request('/runs/'+search.result_run_id+'/sheets','POST',{threshold:search.config.policy?.threshold??85,top_k:display})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Xuất Google Sheet</button><button className="secondary" onClick={async()=>{try{setBenchmark(await request('/v1/searches/'+id+'/benchmark'))}catch(e){setError((e as Error).message)}}}>Đối chiếu nhãn khách</button></div>{!sheetsConnected&&<p>Cần kết nối Google Sheets trong Kết nối & prompt để xuất trực tiếp. CSV có thể tải ngay.</p>}{exports.map(e=><p key={e.id}>{e.status==='COMPLETED'&&e.url?<a href={e.url} target="_blank" rel="noreferrer">Mở Google Sheet</a>:'Trạng thái xuất: '+e.status}{e.error&&' · '+e.error}</p>)}{benchmark&&<div className="notice"><p>{benchmark.status==='INSUFFICIENT_LABELS'?'Chưa đủ nhãn khách xác nhận để kết luận chất lượng.':'Kết quả chỉ có ý nghĩa trên nhãn đã xác nhận.'}</p><p>Recall BE nhóm đầu vào: {benchmark.retrieval.recall_at_input_count==null?'Chưa có dữ liệu':(100*benchmark.retrieval.recall_at_input_count).toFixed(1)+'%'} · Nhãn phù hợp ngoài nhóm: {benchmark.retrieval.good_outside_group.join(', ')||'—'}</p><p>AI Top10: {benchmark.ai_ranking.judged_at_10} đã có nhãn / {benchmark.ai_ranking.unjudged_at_10} chưa có nhãn. Tỉ lệ phù hợp trong phần đã có nhãn: {benchmark.ai_ranking.precision_on_judged_at_10==null?'Chưa có dữ liệu':(100*benchmark.ai_ranking.precision_on_judged_at_10).toFixed(1)+'%'}</p></div>}</details>}{done&&<section className="card sticky-actions"><p>Đã chọn {selected.length} ứng viên{selected.some(s=>!visible.some(r=>r.candidate_id===s))?' (có người ngoài số đang hiển thị)':''}</p><button disabled={busy||!selected.length||!search.is_current} onClick={async()=>{setBusy(true);try{await onCompare(search.result_run_id!,selected)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>So sánh sâu & Recruitability</button></section>}{error&&<p className="notice error">{error}</p>}<details className="card"><summary>Chi tiết lượt chạy và token usage</summary><p>Mã lượt: {id} · {search.attempts} lần thử</p>{search.error&&<p>{search.error}</p>}<pre>{JSON.stringify(search.usage,null,2)}</pre></details></div>;
}
