import React,{useState,useEffect,useRef} from 'react';
import PeopleScouting from './PeopleScouting';
import ScoutingGuidance from './ScoutingGuidance';

type Props={mode?:'pool'|'web';jobId:string;job:any;config:any;dirty:boolean;busy:boolean;ready:number;candidateLimit:number;onCandidateLimit:(n:number)=>void;task:any;strategyCount:number;onStrategyCount:(n:number)=>void;onChange:(fn:(c:any)=>void)=>void;onDraft:(guidanceVersion?:number)=>void;onApprove:()=>void;onPrepare:(guidanceVersion?:number)=>void;onRegenerate:()=>void;onFind:()=>void;onSave:()=>void;onSource:()=>void;renderRule:(rule:any,onChange:(r:any)=>void)=>React.ReactNode};
export default function JobWorkspace({mode='pool',jobId,job,config,dirty,busy,ready,candidateLimit,onCandidateLimit,task,strategyCount,onStrategyCount,onChange,onDraft,onApprove,onPrepare,onRegenerate,onFind,onSave,onSource,renderRule}:Props){
 const [editing,setEditing]=useState(false),[view,setView]=useState<'requirements'|'strategies'>(config.strategies_current?'strategies':'requirements');
 const [guidanceVersion,setGuidanceVersion]=useState<number|undefined>(undefined),[guidanceDirty,setGuidanceDirty]=useState(false);
 const guidanceReady=guidanceVersion!==undefined&&!guidanceDirty;
 const prepare=()=>onPrepare(guidanceVersion);
 const prepared=config.strategies_current&&config.data.strategies.length>=2;
 const waiting=task&&['PENDING','RUNNING'].includes(task.status);
 useEffect(()=>{if(prepared)setView('strategies')},[prepared]);
 const web=mode==='web';
 const scoutingRef=useRef<HTMLDivElement>(null);
 const [scoutingVisit,setScoutingVisit]=useState(0);
 useEffect(()=>{if(scoutingVisit&&view==='strategies'){scoutingRef.current?.scrollIntoView({behavior:'smooth',block:'start'});scoutingRef.current?.focus({preventScroll:true})}},[scoutingVisit,view]);
 const continueFind=web?()=>{setView('strategies');setScoutingVisit(n=>n+1)}:onFind;
 const findLabel=web?(config.approved&&!dirty?'Chọn hướng & tìm trên web':'Xem & duyệt hướng tìm trên web'):(config.approved&&!dirty?'Tìm ứng viên':'Duyệt hướng tìm kiếm & tìm ứng viên');
 const stage=prepared?2:1;
 if(config.input_current===false)return <section className="card"><h2>JD đã thay đổi</h2><p>Yêu cầu đã lưu dùng bản JD cũ. Chuẩn bị yêu cầu mới trước khi tiếp tục để tránh chấm theo dữ liệu cũ.</p>{config.error&&<p className="notice error">{config.error}</p>}<div className="actions"><button disabled={busy||waiting} onClick={onRegenerate}>{waiting?'Đang chuẩn bị…':'Chuẩn bị yêu cầu mới'}</button><button className="secondary" onClick={onSource}>Xem JD gốc</button></div></section>;
 return <div className="job-workspace">
  <div className="workspace-intro"><button className="text-button" onClick={onSource}>Xem JD gốc</button><span className="code">{jobId}</span><h2>{job?.data.title||'Tìm ứng viên cho vị trí này'}</h2><p>{job?.data.summary}</p></div>
  <ol className="journey" aria-label="Các bước tìm ứng viên"><li className={stage===1?'current':'done'}><span>1</span> Xác nhận yêu cầu</li><li className={stage===2?'current':''}><span>2</span> Xem hướng tìm kiếm</li><li><span>3</span> {web?'Tìm hồ sơ trên web':'Chọn ứng viên'}</li></ol>
  <section className="card next-action"><div><h3>{waiting?'AI đang chuẩn bị hướng tìm kiếm':prepared?(web?'Sẵn sàng tìm người trên web':'Sẵn sàng tìm ứng viên'):'Yêu cầu đã được AI đề xuất'}</h3><p>{waiting?'Bạn có thể đọc yêu cầu bên dưới. Trang sẽ tự cập nhật khi hoàn tất.':prepared?(web?'Chọn hướng và kiểm tra truy vấn bên dưới để tìm hồ sơ công khai trên Internet. Không cần kho CV.':'Xem các hướng tìm kiếm bên dưới. Khi bạn đồng ý, BE chọn nhóm hồ sơ đã lưu, sau đó AI đánh giá cả nhóm và mở kết quả.'):'Đọc nhanh danh sách bên dưới. Nếu phù hợp, bạn dùng ngay; chỉ chỉnh những yêu cầu cần thay đổi.'}</p>{dirty&&<p className="unsaved">Có thay đổi chưa lưu. Nút tiếp tục sẽ lưu bản sửa trước.</p>}{task?.status==='FAILED'&&<p role="alert" className="inline-error">Không chuẩn bị được hướng tìm kiếm: {task.error}. Bạn có thể thử lại.</p>}</div><button disabled={busy||waiting||(!prepared&&!guidanceReady)||(prepared&&!ready&&!web)} onClick={prepared?continueFind:prepare}>{busy?'Đang xử lý…':waiting?'Đang chuẩn bị…':prepared?findLabel:dirty?'Lưu & tiếp tục':'Dùng yêu cầu này & tiếp tục'}</button></section>
  {prepared&&!web&&<section className="card"><label>Số ứng viên gửi AI <input aria-label="Số ứng viên gửi AI" type="number" min="1" max="20" value={candidateLimit} onChange={e=>onCandidateLimit(Math.max(1,Math.min(20,+e.target.value)))}/></label><p>Mặc định 20 người, hiển thị 10. Có thể đổi số hiển thị sau khi AI hoàn tất, không tốn thêm call.</p></section>}
  <div className="workspace-tabs"><button className={view==='requirements'?'selected':''} onClick={()=>setView('requirements')}>Yêu cầu tuyển dụng <span>{config.data.criteria.filter((c:any)=>c.enabled).length}</span></button><button className={view==='strategies'?'selected':''} onClick={()=>setView('strategies')}>Hướng tìm kiếm <span>{config.data.strategies.length}</span></button></div>
  <div hidden={view!=='strategies'}><ScoutingGuidance jobId={jobId} used={config.data.scouting_guidance} canGenerate={!busy&&!waiting&&!dirty&&!!config.criteria_approved&&guidanceReady} onGenerate={v=>onPrepare(v)} onState={(v,d)=>{setGuidanceVersion(v);setGuidanceDirty(d)}}/></div>
  {view==='requirements'?<section className="card"><div className="card-head"><div><h3>Ứng viên cần có gì?</h3><p className="muted">Bắt buộc: cần đáp ứng. Ưu tiên: giúp xếp hạng. Thiếu thông tin sẽ được đánh dấu để xác minh.</p></div><button className="secondary" onClick={()=>setEditing(!editing)}>{editing?'Xong chỉnh sửa':'Chỉnh yêu cầu'}</button></div>
   <div className="requirements">{config.data.criteria.map((c:any,i:number)=><div className={'requirement-row '+(!c.enabled?'inactive':'')} key={c.id}><div className="requirement-number">{i+1}</div><div className="requirement-content">{editing?<><label>Tên yêu cầu<input value={c.name} onChange={e=>onChange(x=>x.data.criteria[i].name=e.target.value)}/></label><label>Mô tả<textarea value={c.description} onChange={e=>onChange(x=>x.data.criteria[i].description=e.target.value)}/></label></>:<><strong>{c.name}</strong><p>{c.description}</p></>}{!c.rule&&c.enabled&&<small className="verification-label">Cần recruiter xác minh thêm trong hồ sơ hoặc khi trao đổi.</small>}{editing&&<details><summary>Điều kiện chấm tự động</summary>{renderRule(c.rule,r=>onChange(x=>x.data.criteria[i].rule=r))}</details>}</div><div className="requirement-priority">{editing?<><select aria-label={'Mức quan trọng: '+c.name} value={c.type} onChange={e=>onChange(x=>x.data.criteria[i].type=e.target.value)}><option value="MUST">Bắt buộc</option><option value="NICE">Ưu tiên</option><option value="OPTIONAL">Bổ sung</option></select><label><input type="checkbox" checked={c.enabled} onChange={e=>onChange(x=>x.data.criteria[i].enabled=e.target.checked)}/> Sử dụng</label><button className="text-button" onClick={()=>onChange(x=>x.data.criteria.splice(i,1))}>Xóa</button></>:<span className={'priority '+c.type.toLowerCase()}>{!c.enabled?'Đã tắt':{MUST:'Bắt buộc',NICE:'Ưu tiên',OPTIONAL:'Bổ sung'}[c.type as 'MUST']}</span>}</div></div>)}</div>
   {editing&&<div className="actions"><button className="secondary" onClick={()=>onChange(x=>x.data.criteria.push({id:'C'+Date.now(),name:'Yêu cầu mới',description:'',type:'NICE',enabled:true,rule:null}))}>+ Thêm yêu cầu</button><button disabled={busy||!dirty} onClick={onSave}>Lưu thay đổi</button></div>}
   {!!config.data.review_notes.length&&<details className="review-notes"><summary>Điểm cần kiểm tra trong JD ({config.data.review_notes.length})</summary>{config.data.review_notes.map((n:string,i:number)=><p key={i}>{n}</p>)}</details>}
  </section>:!web?<section className="card"><h3>Chúng tôi sẽ tìm ứng viên theo những hướng này</h3><p className="muted">{web?'Mỗi hướng có một truy vấn công khai. Chọn hướng muốn chạy trong phần tìm web bên dưới.':`Các hướng giúp ưu tiên hồ sơ phù hợp. Toàn bộ ${ready} hồ sơ được BE đối chiếu; AI chỉ đánh giá nhóm đầu vào.`}</p>{config.data.strategies.map((s:any,i:number)=><div className="search-direction" key={s.id}><label><input type="checkbox" checked={s.enabled} onChange={e=>onChange(x=>x.data.strategies[i].enabled=e.target.checked)}/><strong>{s.name}</strong></label><p>{s.description}</p><details><summary>Chỉnh hướng tìm kiếm</summary><input aria-label="Tên hướng tìm kiếm" value={s.name} onChange={e=>onChange(x=>x.data.strategies[i].name=e.target.value)}/><textarea aria-label="Mô tả hướng tìm kiếm" value={s.description} onChange={e=>onChange(x=>x.data.strategies[i].description=e.target.value)}/>{renderRule(s.rule,r=>onChange(x=>x.data.strategies[i].rule=r))}</details></div>)}</section>:null}
  {view==='strategies'&&<div ref={scoutingRef} tabIndex={-1} style={{scrollMarginTop:24}} aria-label="Chọn hướng tìm hồ sơ công khai"><PeopleScouting jobId={jobId} config={config} dirty={dirty} busy={busy} task={task} onChange={onChange} onSave={onSave} onApprove={onApprove} guidanceReady={guidanceReady} onDraft={()=>onDraft(guidanceVersion)}/></div>}
  <details className="card advanced-settings"><summary>Thiết lập nâng cao</summary><p className="muted">Chỉ cần thay đổi khi muốn điều chỉnh cách lọc và xếp hạng. Các giá trị hiện tại chưa được xác nhận bằng nhãn đánh giá của khách.</p><div className="actions"><label>Số hướng tìm kiếm<input type="number" min="2" max="20" value={strategyCount} onChange={e=>onStrategyCount(Math.min(20,Math.max(2,+e.target.value)))}/></label><label>Điều kiện bắt buộc<select value={config.data.policy.gate} onChange={e=>onChange(x=>x.data.policy.gate=e.target.value)}><option value="ALL_MET">Đáp ứng đầy đủ</option><option value="NO_CONFIRMED_FAILURE">Cho phép đáp ứng một phần</option><option value="REVIEW_ONLY">Chỉ cảnh báo để review</option></select></label><label><input type="checkbox" checked={config.data.policy.threshold_enabled} onChange={e=>onChange(x=>x.data.policy.threshold_enabled=e.target.checked)}/> Lọc theo điểm</label><select aria-label="Cách so sánh điểm" value={config.data.policy.threshold_operator} onChange={e=>onChange(x=>x.data.policy.threshold_operator=e.target.value)}><option>{'>'}</option><option>{'>='}</option></select><label>Điểm tối thiểu<input type="number" min="0" max="100" value={config.data.policy.threshold} onChange={e=>onChange(x=>x.data.policy.threshold=+e.target.value)}/></label><label>Số hồ sơ đề xuất<input type="number" min="1" value={config.data.policy.top_k} onChange={e=>onChange(x=>x.data.policy.top_k=+e.target.value)}/></label><label>Mức ảnh hưởng của hướng tìm<input type="number" min="0" max="1" step=".05" value={config.data.policy.alpha} onChange={e=>onChange(x=>x.data.policy.alpha=+e.target.value)}/></label>{['MUST','NICE','OPTIONAL'].map(k=><label key={k}>Trọng số {{MUST:'bắt buộc',NICE:'ưu tiên',OPTIONAL:'bổ sung'}[k as 'MUST']}<input type="number" min=".1" step=".5" value={config.data.policy.weights[k]} onChange={e=>onChange(x=>x.data.policy.weights[k]=+e.target.value)}/></label>)}</div></details>
  {!(web && view==='strategies') && <><div className="workspace-footer"><span>{waiting?'Đang chuẩn bị, kết quả sẽ tự cập nhật':dirty?'Bạn có thay đổi chưa lưu':prepared?'Đã có hướng tìm kiếm để bạn xem':'Bạn có thể dùng ngay yêu cầu đề xuất'}</span><button disabled={busy||waiting||(!prepared&&!guidanceReady)||(prepared&&!ready&&!web)} onClick={prepared?continueFind:prepare}>{busy?'Đang xử lý…':waiting?'Đang chuẩn bị…':prepared?findLabel:'Tiếp tục'}</button></div></>}
 </div>;
}
