import SearchTypeSelector,{type SearchType,searchTypeLabel} from './SearchType';
import React,{useEffect,useState} from 'react';
import {request} from './request';
import PublicAssessment from './PublicAssessment';
import AllSourceAssessment from './AllSourceAssessment';
import LocationSelector,{type LocationScope,effectiveQuery,scopeLabel} from './LocationScope';
export default function PeopleScouting({jobId,config,dirty,busy,task,guidanceReady=true,onChange,onSave,onApprove,onDraft}:{jobId:string;config:any;dirty:boolean;busy:boolean;task:any;guidanceReady?:boolean;onChange:(fn:(c:any)=>void)=>void;onSave:()=>void;onApprove:()=>void;onDraft:()=>void}){
 const [selected,setSelected]=useState<string[]>([]),[group,setGroup]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const working=group?.status==='RUNNING', drafting=task?.kind==='exa_queries'&&['PENDING','RUNNING'].includes(task.status);
 const [searchType,setSearchType]=useState<SearchType>('auto');
 const [locationScope,setLocationScope]=useState<LocationScope|null>('VIETNAM');
 const strategies=config.data.strategies;
 const musts=config.data.public_musts||[];
 const mustIds=config.data.criteria.filter((c:any)=>c.enabled&&c.type==='MUST').map((c:any)=>c.id);
 const complete=mustIds.length===musts.length&&mustIds.every((id:string)=>musts.some((m:any)=>m.criterion_id===id&&m.query?.trim()));
 const composed=(q:string)=> (musts.length?'Required professional experience: '+musts.map((m:any)=>m.query.trim()).join('; ')+'. ':'')+q.trim();
 const loadHistory=()=>request<any[]>('/v1/jobs/'+jobId+'/people-searches').then(setHistory);
 useEffect(()=>{loadHistory().catch(e=>setError(e.message))},[jobId]);
 useEffect(()=>{setSelected(ids=>ids.filter(id=>strategies.some((s:any)=>s.id===id&&s.enabled)))},[config.version]);
 useEffect(()=>{if(!working)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const value=await request('/v1/people-searches/'+group.id);if(active){setGroup(value);timer=setTimeout(poll,1500)}}catch(e){if(active){setError((e as Error).message);timer=setTimeout(poll,3000)}}};poll();return()=>{active=false;clearTimeout(timer)}},[group?.id,working]);
 const act=async(fn:()=>Promise<any>)=>{setLoading(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const find=(refresh=false)=>act(async()=>{const g=await request('/v1/jobs/'+jobId+'/people-searches','POST',{config_version:config.version,strategy_ids:selected,refresh,search_type:searchType,location_scope:locationScope});setGroup(g);await loadHistory()});
 return <section className="card"><h2>Tìm hồ sơ công khai qua Exa People</h2><p>Chọn hướng tìm, kiểm tra truy vấn rồi gửi Exa. Kết quả là nguồn hồ sơ công khai — chưa đánh giá phù hợp JD.</p><p className="muted">Không đưa tên khách, thông tin liên hệ, lương hoặc private note vào truy vấn.</p>
 <h3>MUST công khai dùng cho mọi hướng tìm</h3>{!complete&&<div className="notice warn" role="status"><p>Chưa thể tìm: các hướng cũ chưa có đầy đủ yêu cầu bắt buộc (MUST). Bổ sung truy vấn, kiểm tra rồi duyệt trước khi chạy.</p><button className="secondary" disabled={!guidanceReady||busy||loading||dirty||drafting||!!working||!config.criteria_approved||!config.strategies_current} onClick={onDraft}>{drafting?'Đang bổ sung MUST…':'Bổ sung MUST cho các hướng tìm (AI)'}</button>{dirty&&<p>Lưu bản sửa trước khi bổ sung MUST.</p>}</div>}{musts.map((m:any,i:number)=><label key={m.criterion_id} style={{display:'block'}}>{config.data.criteria.find((c:any)=>c.id===m.criterion_id)?.name}<textarea value={m.query} disabled={busy||loading||!!working} onChange={e=>onChange(c=>{c.data.public_musts[i].query=e.target.value})}/></label>)}
 <SearchTypeSelector value={searchType} onChange={setSearchType} disabled={busy||loading||!!working}/><LocationSelector value={locationScope} onChange={setLocationScope} disabled={busy||loading||!!working}/>{strategies.map((s:any,i:number)=><div className="search-direction" key={s.id}><label><input aria-label={'Chọn chạy Exa '+s.id} type="checkbox" checked={selected.includes(s.id)} disabled={!s.enabled||!!working||loading} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(x=>x!==s.id))}/> <strong>{s.name}</strong>{!s.enabled?' · Đã tắt':''}</label><p>{s.description}</p><label>Truy vấn gửi Exa<textarea aria-label={'Truy vấn Exa '+s.id} maxLength={1500} value={s.exa_query||''} disabled={busy||loading||!!working||drafting} placeholder="Chưa có truy vấn. Bấm Soạn truy vấn Exa bên dưới." onChange={e=>onChange(c=>c.data.strategies[i].exa_query=e.target.value)}/></label><p className="muted">Truy vấn thực tế sẽ gửi ({effectiveQuery(composed(s.exa_query||''),locationScope).length}/1.500 ký tự):</p><blockquote style={{overflowWrap:'anywhere'}}>{effectiveQuery(composed(s.exa_query||''),locationScope)}</blockquote><button className="secondary" disabled={!s.exa_query} onClick={()=>act(()=>navigator.clipboard.writeText(effectiveQuery(composed(s.exa_query),locationScope)))}>Sao chép truy vấn {s.id}</button></div>)}
 <div className="actions"><button className="secondary" disabled={!guidanceReady||busy||loading||dirty||drafting||!!working||!config.criteria_approved||!config.strategies_current} onClick={onDraft}>{drafting?'Đang soạn truy vấn…':'Soạn truy vấn Exa'}</button><button className="secondary" disabled={busy||loading||!dirty||drafting} onClick={onSave}>Lưu truy vấn</button></div>
 {dirty?<p className="notice warn">Lưu bản sửa rồi duyệt trước khi chạy Exa.</p>:!config.approved?<p className="notice warn">Kiểm tra và duyệt hướng tìm kiếm trước khi gửi.</p>:null}
 {task?.kind==='exa_queries'&&task.status==='FAILED'&&<p role="alert" className="notice error">{task.error}</p>}
 <p>Đã chọn {selected.length} hướng tìm · mỗi hướng lấy tối đa 10 nguồn hồ sơ công khai. Đây là số nguồn tìm kiếm, chưa phải số ứng viên đạt yêu cầu.</p>
 {!config.approved&&!dirty&&<div className="notice warn" role="status"><p>Bước tiếp theo: xác nhận các hướng và truy vấn bạn vừa xem. Duyệt xong mới có thể gửi tìm kiếm.</p><button disabled={busy||loading||drafting||!config.strategies_current||!complete} onClick={onApprove}>{busy?'Đang xác nhận…':'Xác nhận hướng tìm kiếm'}</button></div>}
 {!!config.approved&&!selected.length&&<p className="notice warn">Chọn ít nhất một hướng tìm bằng ô checkbox phía trên.</p>}
 {!!config.approved&&selected.some(id=>effectiveQuery(composed(strategies.find((s:any)=>s.id===id)?.exa_query||''),locationScope).length>1500)&&<p role="alert" className="notice error">Truy vấn đã chọn vượt 1.500 ký tự sau khi ghép MUST và địa điểm. Rút gọn rồi lưu và duyệt lại.</p>}
 <details><summary>Thông tin cache và thử lại</summary><p>Cùng đầu vào có thể dùng lại kết quả đã lưu; lỗi kết nối được thử tối đa 3 lần mỗi lượt.</p></details>
 <div className="actions"><button disabled={busy||loading||!!working||drafting||dirty||!config.approved||!complete||!locationScope||!selected.length||selected.some(id=>!strategies.find((s:any)=>s.id===id)?.exa_query?.trim()||effectiveQuery(composed(strategies.find((s:any)=>s.id===id)?.exa_query||''),locationScope).length>1500)} onClick={()=>find()}>{working?'Exa đang tìm…':'Tìm hồ sơ qua Exa'}</button>{group&&<button className="secondary" disabled={loading||working||busy||dirty||!config.approved||!complete||!locationScope||!selected.length||selected.some(id=>!strategies.find((s:any)=>s.id===id)?.exa_query?.trim()||effectiveQuery(composed(strategies.find((s:any)=>s.id===id)?.exa_query||''),locationScope).length>1500)} onClick={()=>find(true)}>Tìm mới nhóm đã chọn (có phí)</button>}</div>
 {error&&<p role="alert" className="notice error">{error}</p>}
 {group&&<><p>Chế độ của kết quả: <b>{searchTypeLabel(group.snapshot.search_type)}</b></p><p><b>Phạm vi của kết quả: {scopeLabel(group.snapshot.location_scope)}</b></p><h3>{group.status==='RUNNING'?'Đang tìm theo từng hướng':group.status==='COMPLETED'?'Đã hoàn tất nhóm tìm':'Nhóm tìm có lượt chưa hoàn tất'}</h3>{!group.is_current&&<p className="notice warn">JD/yêu cầu đã thay đổi. Kết quả này giữ bản cũ; chọn strategy hiện tại và tìm lại để cập nhật.</p>}<p>Phí Exa đã báo cho các lượt của nhóm: ${group.known_cost_dollars.toFixed(5)}{group.has_unreported_cost?' · Có lượt chưa xác định phí.':''}</p>{group.items.map((item:any)=><div className="assessment" key={item.strategy.id}><b>{item.strategy.name} · {item.search.status}</b><p>{item.search.effective_query||item.strategy.effective_query||item.strategy.exa_query}</p>{item.search.error&&<p className="notice error">{item.search.error}</p>}{['FAILED','INTERRUPTED'].includes(item.search.status)&&<button disabled={loading||item.search.attempts>=3} onClick={()=>act(async()=>{await request('/v1/web-searches/'+item.search.id+'/retry','POST');setGroup(await request('/v1/people-searches/'+group.id))})}>Thử lại hướng này</button>}</div>)}{['COMPLETED','PARTIAL'].includes(group.status)&&group.is_current&&!!group.results.length&&<><AllSourceAssessment key={group.id} searchId={group.id} jobId={jobId} version={config.version} total={group.results.length}/><details><summary>Chấm nhóm riêng / bổ sung PDF / lịch sử lượt chấm cũ</summary><PublicAssessment key={group.id} searchId={group.id} sources={group.results} initialJob={jobId} jobs={[{id:jobId,status:'READY',data:{title:'JD hiện tại'}}]} onJob={()=>{}}/></details></>}<h3>{group.results.length} nguồn hồ sơ tìm được · dữ liệu tìm kiếm</h3>{!group.results.length&&!working&&<p>Chưa có nguồn để hiển thị; kiểm tra từng lượt phía trên hoặc sửa truy vấn.</p>}{group.results.map((r:any)=><article className="assessment" key={r.url}><h3><a href={r.url} target="_blank" rel="noreferrer">{r.title||r.url}</a></h3><small style={{overflowWrap:'anywhere'}}>{r.url}</small><p className="verification-label">Địa điểm cần xác minh</p><p>Tìm thấy qua: {r.strategy_ids.map((id:string)=>group.items.find((x:any)=>x.strategy.id===id)?.strategy.name||id).join(' · ')}</p><small>Lấy nguồn: {new Date(r.retrieved_at).toLocaleString('vi-VN')}</small>{r.highlights.map((h:string,i:number)=><div key={i}><p>{h.slice(0,260)}{h.length>260?'…':''}</p>{h.length>260&&<details><summary>Xem toàn bộ đoạn trích</summary><blockquote style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{h}</blockquote></details>}</div>)}</article>)}</>}
 <details><summary>Lịch sử tìm People cho JD này ({history.length})</summary>{history.map(h=><div className="actions" key={h.id}><small>{new Date(h.created).toLocaleString('vi-VN')}</small><button className="secondary" disabled={loading||working} onClick={()=>act(async()=>{const g=await request<any>('/v1/people-searches/'+h.id);setGroup(g);setLocationScope(g.snapshot.location_scope||null);setSearchType(g.snapshot.search_type||'auto')})}>Mở nhóm tìm</button></div>)}</details></section>;
}
