import React,{useEffect,useState} from 'react';
import {request} from './request';
const names:Record<string,string>={MET:'Đáp ứng',PARTIAL:'Một phần',NOT_MET:'Có bằng chứng không đáp ứng',UNKNOWN:'Chưa đủ thông tin'};
export default function PublicAssessment({searchId,jobs,onJob}:{searchId:string;jobs:any[];onJob:(id:string)=>void}){
 const [job,setJob]=useState(''),[config,setConfig]=useState<any>(null),[report,setReport]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[limit,setLimit]=useState(10);
 useEffect(()=>{setConfig(null);setReport(null);setError('');if(!job)return;let active=true;Promise.all([request<any>('/jobs/'+job+'/config'),request<any[]>('/v1/public-assessments?job_id='+encodeURIComponent(job)+'&search_id='+encodeURIComponent(searchId))]).then(([v,history])=>{if(active){setConfig(v);setReport(history[0]||null)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[job,searchId]);
 useEffect(()=>{if(report?.results?.length)setLimit(n=>Math.min(n,report.results.length))},[report?.id,report?.results?.length]);
 const working=report&&['PENDING','RUNNING'].includes(report.status);
 useEffect(()=>{if(!working)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await request<any>('/v1/public-assessments/'+report.id);if(active){setReport(r);if(['PENDING','RUNNING'].includes(r.status))timer=setTimeout(poll,1500)}}catch(e){if(active){setError((e as Error).message);timer=setTimeout(poll,3000)}}};poll();return()=>{active=false;clearTimeout(timer)}},[report?.id,!!working]);
 const start=async(retry=false)=>{setBusy(true);setError('');try{setReport(await request(retry?'/v1/public-assessments/'+report.id+'/retry':'/v1/public-assessments','POST',retry?undefined:{job_id:job,config_version:config.version,search_id:searchId}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="assessment"><h3>Đánh giá các nguồn này theo JD</h3><p>AI chỉ đọc đoạn trích đã tìm được. Điểm sơ bộ chưa thay thế việc xem CV hoặc xác minh với ứng viên; thiếu bằng chứng giữ “chưa đủ thông tin”. Không nhập người vào kho CV.</p>
 <label>JD dùng để đánh giá<select aria-label="JD chấm nguồn công khai" value={job} disabled={busy||!!working} onChange={e=>setJob(e.target.value)}><option value="">Chọn vị trí tuyển dụng…</option>{jobs.filter(j=>j.status==='READY').map(j=><option key={j.id} value={j.id}>{j.id} · {j.data.title||j.id}</option>)}</select></label>
 {job&&(!config||!config.criteria_approved||config.input_current===false)&&<p className="notice warn">{!config?'Đang tải yêu cầu JD…':'JD chưa xác nhận hoặc đã đổi.'} <button className="secondary" disabled={busy||!!working} onClick={()=>onJob(job)}>Mở JD & xác nhận yêu cầu</button></p>}
 <button disabled={busy||!!working||!config?.criteria_approved||config.input_current===false} onClick={()=>start()}>{working?'AI đang đối chiếu các nguồn…':'Đánh giá nhóm hồ sơ theo JD (có phí AI)'}</button>
 {error&&<p className="notice error" role="alert">{error}</p>}
 {report&&<><p role="status">{working?'Đang đánh giá - không cần bấm lại.':report.status==='COMPLETED'?'Đã hoàn tất đánh giá sơ bộ.':'Chưa hoàn tất đánh giá.'} · {report.source_count} nguồn · {report.provider}/{report.model}</p>{!report.is_current&&<p className="notice warn">JD đã đổi. Kết quả giữ yêu cầu cũ; tải JD hiện tại trước khi đánh giá lại.</p>}{report.error&&<p className="notice error">{report.error}</p>}{['FAILED','INTERRUPTED'].includes(report.status)&&<button disabled={busy||report.attempts>=3||!report.is_current} onClick={()=>start(true)}>Thử lại đánh giá ({report.attempts}/3)</button>}
 {!!report.results?.length&&<><label>Hiển thị<select aria-label="Số nguồn đã chấm hiển thị" value={limit} onChange={e=>setLimit(+e.target.value)}>{Array.from({length:report.results.length},(_,i)=>i+1).map(n=><option value={n} key={n}>{n} nguồn</option>)}</select></label><p className="muted">Đổi số hiển thị dùng kết quả đã lưu, không gọi AI lại. Điểm phản ánh bằng chứng trong đoạn trích; không phải xác suất tuyển thành công.</p>{report.results.slice(0,limit).map((r:any)=><article className="search-direction" key={r.candidate_id}><div className="card-head"><h3><a href={r.url} target="_blank" rel="noreferrer">{r.title||r.url}</a></h3><strong>{r.score??'—'} / 100</strong></div><p>Độ phủ bằng chứng: {r.coverage}% · Nguồn công khai chưa xác minh</p><details><summary>Xem tiêu chí, bằng chứng và điểm cần hỏi</summary>{r.assessments.map((a:any)=><div className="assessment" key={a.criterion_id}><b>{report.criteria.find((c:any)=>c.id===a.criterion_id)?.name||a.criterion_id}: {names[a.status]}</b><p>{a.explanation}</p>{a.evidence?.map((e:any,i:number)=><blockquote key={i} style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{e.quote}</blockquote>)}{a.status==='UNKNOWN'&&<p>Cần hỏi ứng viên để xác minh tiêu chí này.</p>}</div>)}</details></article>)}<small>Usage AI: {report.usage?.total_tokens??'Provider chưa báo'} token. Phí AI chưa xác định nếu provider không trả.</small></>}
 </>}
 </div>;
}
