import React,{useEffect,useState} from 'react';
import {request} from './request';
type Ticket={ticket_id:string;status:string;search_id?:string;error?:string};
export default function SingleCVUpload({jobId,version,approved,onResult}:{jobId:string;version:number;approved:boolean;onResult:(id:string)=>void}){
 const [file,setFile]=useState<File|null>(null),[note,setNote]=useState(''),[ticket,setTicket]=useState<Ticket|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const working=!!ticket&&['PENDING','RUNNING'].includes(ticket.status);
 useEffect(()=>{if(!ticket||!working)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const t=await request<Ticket>('/v1/cv-assessments/'+ticket.ticket_id);if(!active)return;setTicket(t);setError('');if(t.search_id){onResult(t.search_id);return;}if(['PENDING','RUNNING'].includes(t.status))timer=setTimeout(poll,1500);}catch(e){if(active){setError((e as Error).message);timer=setTimeout(poll,3000);}}};poll();return()=>{active=false;clearTimeout(timer);};},[ticket?.ticket_id,working]);
 const submit=async()=>{if(!file)return;setError('');if(file.size>15*1024*1024){setError('Chọn CV PDF tối đa 15 MB.');return;}setBusy(true);try{const body=new FormData();body.append('file',file);body.append('config_version',String(version));body.append('private_note',note);const t=await request<Ticket>('/v1/jobs/'+encodeURIComponent(jobId)+'/cv-assessments','POST',body);setTicket(t);if(t.search_id)onResult(t.search_id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const retry=async()=>{if(!ticket)return;setBusy(true);try{setTicket(await request<Ticket>('/v1/cv-assessments/'+ticket.ticket_id+'/retry','POST'));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="card"><div className="card-head"><div><span className="code">{jobId}</span><h2>CV này có phù hợp với job?</h2></div></div><p>Tải một CV lên để AI đối chiếu với yêu cầu tuyển dụng đã xác nhận. Bạn sẽ thấy mức đáp ứng, bằng chứng và những điểm cần hỏi thêm.</p>{!approved&&<p className="notice warn">Xác nhận yêu cầu tuyển dụng bên dưới trước khi đánh giá CV. Không cần duyệt hướng tìm kiếm để đánh giá riêng một người.</p>}<label>CV PDF (tối đa 15 MB)<input type="file" accept=".pdf,application/pdf" aria-label="CV để đánh giá với JD" disabled={busy||working} onChange={e=>{setFile(e.target.files?.[0]??null);setTicket(null);setError('');}}/></label><details><summary>Thêm ghi chú riêng về ứng viên (không bắt buộc)</summary><textarea aria-label="Ghi chú riêng cho CV" maxLength={30000} value={note} disabled={busy||working} placeholder="Ví dụ: mong muốn công việc hoặc thông tin đã trao đổi với ứng viên" onChange={e=>{setNote(e.target.value);setTicket(null);}}/></details><p className="muted">CV được lưu vào hồ sơ ứng viên để dùng lại. Lượt này chỉ đánh giá CV bạn tải lên, không chạy lại cả kho hồ sơ.</p>{(error||ticket?.error)&&<p className="notice error" role="alert">{error||ticket?.error}</p>}{working&&<p role="status">Đang đọc và chuẩn hóa CV. Sau đó AI sẽ tự đánh giá với {jobId}; bạn không cần bấm lại.</p>}<div className="actions"><button onClick={submit} disabled={!approved||!file||busy||working}>{busy?'Đang tải lên…':working?'Đang xử lý CV…':'Đánh giá CV với job này'}</button>{ticket&&['FAILED','INTERRUPTED'].includes(ticket.status)&&<button className="secondary" disabled={busy||!approved} onClick={retry}>Thử xử lý CV lại</button>}</div></section>;
}
