// Shared API contracts. Update here when changing backend response schemas.
export type Policy={gate:string;threshold_enabled:boolean;threshold:number;threshold_operator:string;weights:Record<string,number>;alpha:number;top_k:number;calibrated:boolean};
export type Rule={mode:string;predicates:{field:string;operator:string;values:string[];number:number|null;weight:number}[]};
export type Evidence={source_id:string;quote:string};
export type Signal={topic:string;summary:string;evidence:Evidence[]};
export type Profile={id:string;kind:string;revision:number;status:string;data:{title?:string;summary?:string;skills?:string[];domains?:string[];signals?:Signal[];unknowns?:string[];contradictions?:string[];error?:string;facts?:{id:string;field:string;value:string;evidence:Evidence[]}[];_meta?:{schema_version?:number;correction_review_required?:boolean}};sources?:Source[]};
export type Source={source_id:string;name:string;url:string;text:string;revision:number;group:string};
export type Config={input_current?:boolean;error?:string;job_id:string;version:number;approved:number;criteria_approved:number;strategies_current:boolean;data:{criteria:{id:string;name:string;type:string;enabled:boolean;description:string;rule?:Rule|null}[];policy?:Policy;strategies:{exa_query?:string;id:string;name:string;description:string;enabled:boolean;rule?:Rule|null}[];review_notes:string[]}};
export type Assessment={criterion_id:string;status:string;evidence:Evidence[];explanation:string};
export type Eval={candidate_id:string;status:string;error:string;data:{score:number|null;coverage:number;must_complete:boolean;must_passed:boolean;must_failure?:boolean;must_partial?:boolean;lane?:string;retrieval_score?:number;strategy_score?:number;strategy_details?:{strategy_id:string;score:number;evidence:Evidence[]}[];assessments:Assessment[];strengths:string[];gaps:string[];strategy_ids:string[]}|null};
export type Report={provider:string;model:string;prompt_version:string;id:string;status:string;error?:string;selected:string[];is_current?:boolean;data?:{overall_summary:string;items:{candidate_id:string;rank:number;recommendation:string;technical_evidence:Evidence[];strengths:string[];gaps:string[];recruitability:{conclusion:string;summary:string;evidence:Evidence[];attractions:Signal[];barriers:Signal[];hypotheses:string[];questions:string[]}}[]}};
export type Run={engine?:string;metrics?:{seconds:number;llm_calls:number;pdf_reads:number};provider:string;source_files?:FileRow[];id:string;job_id:string;status:string;model:string;created:string;updated?:string;config_version:number;prompt_version:string;error?:string;total?:number;is_current?:boolean;config?:Config['data'];evaluations?:Eval[];reports?:Report[];candidate_profiles?:Record<string,Profile['data']>};
export type FileRow={id:string;name:string;url:string;group_name:string;entity_id:string|null;status:string;error:string|null;revision:number;available:number;modified?:string;extraction?:{method:string;review_required:boolean}};
export type Provider={id:string;label:string;key_env:string;env_file:string;configured:boolean};
export type Status={preparation_errors?:Record<string,string>;architecture?:string;storage?:string;backfill?:{extraction_calls:number;candidate_calls:number;criteria_calls:number};provider:string;usage_by_provider:Record<string,{requests:number;total_tokens:number}>;profiles:{kind:string;status:string;n:number}[];files:number;google_connected:boolean;sheets_connected:boolean;source_mode:string;model:string;prompt_version:string;last_sync:{at:string;mode:string;files:number;errors:number}|null;sync_progress:{processed:number;total:number;current:string}|null;ai:{ok?:boolean;error?:string;available_models?:string[]};tasks:{id:number;kind:string;status:string;error?:string;payload?:string}[];usage:{requests:number;total_tokens:number;prompt_tokens:number;completion_tokens:number}};
